// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATQPWQWkXVWHhRvKb3CPQ3BaOfVwumDZs',
    appId: '1:216406330323:web:8045e6a0dc12759162bd26',
    messagingSenderId: '216406330323',
    projectId: 'projeto-prod-18980',
    authDomain: 'projeto-prod-18980.firebaseapp.com',
    storageBucket: 'projeto-prod-18980.appspot.com',
    measurementId: 'G-CV5WBNZP4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxpHa592BMO5TVKlRsSRfCTFG4VwZV0fw',
    appId: '1:216406330323:android:99f1ea8d45b7f4e362bd26',
    messagingSenderId: '216406330323',
    projectId: 'projeto-prod-18980',
    storageBucket: 'projeto-prod-18980.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANGyD9DWrlhtunMdksA7vP9oVuvrJ0cao',
    appId: '1:216406330323:ios:b14437298c9a5ef562bd26',
    messagingSenderId: '216406330323',
    projectId: 'projeto-prod-18980',
    storageBucket: 'projeto-prod-18980.appspot.com',
    iosBundleId: 'com.example.produtoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANGyD9DWrlhtunMdksA7vP9oVuvrJ0cao',
    appId: '1:216406330323:ios:b14437298c9a5ef562bd26',
    messagingSenderId: '216406330323',
    projectId: 'projeto-prod-18980',
    storageBucket: 'projeto-prod-18980.appspot.com',
    iosBundleId: 'com.example.produtoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATQPWQWkXVWHhRvKb3CPQ3BaOfVwumDZs',
    appId: '1:216406330323:web:f97be53314725a6262bd26',
    messagingSenderId: '216406330323',
    projectId: 'projeto-prod-18980',
    authDomain: 'projeto-prod-18980.firebaseapp.com',
    storageBucket: 'projeto-prod-18980.appspot.com',
    measurementId: 'G-Z632PQJ94B',
  );
}
